# -*- coding: utf-8 -*-
"""LVADSUSR133-ADITYA.V-predictive analysis-K means clustering -ia2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ti3_4AxnR4a4TLbRYlDHGqSklDHDRFub
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Load the dataset
data = pd.read_csv('/content/Mall_Customers.csv')

# Display the first few rows of the dataset
print("Original dataset:")
print(data.head())

# Check for missing values
print("\nMissing values before imputation:")
print(data.isnull().sum())

# Separate numerical and categorical columns
numerical_cols = ['Age', 'Annual Income (k$)', 'Spending Score (1-100)']
categorical_cols = ['Gender']

# Preprocessing pipeline
numerical_transformer = SimpleImputer(strategy='mean')
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

# Apply preprocessing
data_preprocessed = pd.DataFrame(preprocessor.fit_transform(data))

# Replace missing values with mean (only for numerical columns)
data_preprocessed.fillna(data_preprocessed.mean(), inplace=True)

# Data normalization
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_preprocessed)

# EDA statistics
print("\nEDA statistics:")
print(data_preprocessed.describe())

# EDA visualization
# Pairplot of selected features
sns.pairplot(data_preprocessed)
plt.show()

# Determine the optimal number of clusters using the elbow method
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(data_scaled)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

# Determine the optimal number of clusters using silhouette score
silhouette_scores = []
for n_clusters in range(2, 11):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    cluster_labels = kmeans.fit_predict(data_scaled)
    silhouette_avg = silhouette_score(data_scaled, cluster_labels)
    silhouette_scores.append(silhouette_avg)
optimal_n_clusters = silhouette_scores.index(max(silhouette_scores)) + 2
print("Optimal number of clusters (Silhouette score):", optimal_n_clusters)

# Apply k-means clustering with the optimal number of clusters
kmeans = KMeans(n_clusters=optimal_n_clusters, init='k-means++', random_state=42)
cluster_labels = kmeans.fit_predict(data_scaled)
data['Cluster'] = cluster_labels

# Cluster profiling
cluster_profile = data.groupby('Cluster').mean()
print("\nCluster profile:")
print(cluster_profile)

# Feature engineering: Add new feature - Ratio of Spending to Income
data_preprocessed['Spending_Income_Ratio'] = data_preprocessed[2] / data_preprocessed[1]

"""Cluster 0 (Young Low Spenders):

Targeted Marketing Strategies: Focus on offering budget-friendly deals and discounts, as these customers have relatively lower annual incomes and spending scores. Promotions such as student discounts or limited-time offers can appeal to this segment.
Customer Experience Improvement: Enhance the value proposition for this segment by providing personalized recommendations based on their preferences and introducing loyalty programs to incentivize repeat purchases.

Cluster 1 (Middle-Aged Moderate Spenders):

Targeted Marketing Strategies: Offer a diverse range of products or services catering to the needs and preferences of middle-aged individuals. Leverage targeted advertising campaigns on platforms that this demographic frequently engages with.
Customer Experience Improvement: Implement omnichannel strategies to provide seamless shopping experiences across online and offline channels. Enhance product visibility and accessibility through intuitive website design and convenient store layouts.

Cluster 2 (Elderly Moderate Spenders):

Targeted Marketing Strategies: Create marketing campaigns that resonate with the interests and lifestyles of elderly customers. Emphasize product reliability, quality, and convenience in your messaging.
Customer Experience Improvement: Provide personalized assistance and support to accommodate the unique needs of elderly customers. Offer discounts or special services tailored to this segment, such as senior citizen discounts or priority assistance.

Cluster 3 (Young Low Spenders - Low Income):

Targeted Marketing Strategies: Develop cost-effective offerings and bundle deals to appeal to price-sensitive customers. Utilize social media platforms and influencer marketing to reach this demographic effectively.
Customer Experience Improvement: Streamline the purchasing process and provide transparent pricing information to build trust with customers. Collect feedback to identify areas for improvement and enhance customer satisfaction.

Cluster 4 (Young High Spenders):

Targeted Marketing Strategies: Showcase premium products or exclusive collections to attract these high-spending customers. Launch targeted digital marketing campaigns on social media platforms frequented by young adults.
Customer Experience Improvement: Create immersive shopping experiences both online and offline, incorporating elements of personalization and exclusivity. Offer rewards or VIP programs to incentivize continued engagement and loyalty.

Cluster 5 (Young Moderate Spenders):

Targeted Marketing Strategies: Emphasize value-based messaging and promotions that appeal to young, price-conscious consumers. Engage with this segment through social media platforms and influencer collaborations.
Customer Experience Improvement: Enhance the online shopping experience with user-friendly interfaces and mobile optimization. Implement interactive features such as live chat support to address customer inquiries promptly.

Cluster 6 (Young High Spenders - High Income):

Targeted Marketing Strategies: Position luxury or premium offerings to capture the attention of affluent young consumers. Utilize influencer partnerships and experiential marketing to reinforce brand image and exclusivity.
Customer Experience Improvement: Provide personalized shopping experiences both online and offline, offering concierge services and exclusive events. Focus on building long-term relationships through exceptional service and customized offerings.

Cluster 7 (Middle-Aged Moderate Spenders - Moderate Income):

Targeted Marketing Strategies: Highlight products or services that offer a balance of quality and affordability to appeal to this demographic. Leverage email marketing and loyalty programs to maintain customer engagement.
Customer Experience Improvement: Enhance product education and support services to assist customers in making informed purchasing decisions. Implement feedback mechanisms to gather insights and continuously improve the shopping experience.

Cluster 8 (Young Moderate Spenders - Moderate Income):

Targeted Marketing Strategies: Offer versatile and trendy products that align with the preferences of young, fashion-conscious consumers. Leverage social media platforms and influencer collaborations to drive brand awareness.
Customer Experience Improvement: Invest in interactive shopping experiences and user-generated content to foster community engagement. Implement seamless omnichannel integration to provide a cohesive brand experience across all touchpoints.

Cluster 9 (Young High Spenders - Low Income):

Targeted Marketing Strategies: Create value-driven promotions and bundle deals to attract young customers with limited disposable income. Utilize digital marketing channels such as social media advertising and content marketing to reach this segment.
Customer Experience Improvement: Optimize the online shopping experience for mobile devices and provide flexible payment options to accommodate budget-conscious consumers. Offer educational resources and styling tips to enhance the perceived value of products.
These targeted marketing strategies and customer experience improvement initiatives are designed to address the unique needs and preferences of each cluster, ultimately driving engagement, loyalty, and profitability.








"""

