# -*- coding: utf-8 -*-
"""Python_Assessment - 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CeSsnifj9SXZGD7rkg6p-VP0d4X4UGel
"""

#1
def area_rectangle(length, breath):

  area=length*breath
  return area

area_rectangle(1,2)

#2
def BMI(height, weight):

  bmi=weight/(height**2)
  return float(bmi)

BMI(181,75)

#3

dict_1={"aditya":[45,65,45], "preethi":[23,56,78],"drax":[45,78,98]}

for i in dict_1.keys():
  print(i,dict_1[i])

#4
age=int(input("please enter yopur age"))

if age<18:
  print("you are a minor")
elif age>=18 and age <60:
  print("you are an adult")
elif age>=60:
  print("you are a senior")

#5
for i in range(1,51):
  if(i%2==0):
    print(i)

#6

password=input("any password with atleast 8 characters")

RP='FALSE'

while(RP=='FALSE'):
  if(len(password)>=8):
    print("your password is accpeted")
    RP="TRUE"
  else:
    password=input("please reenter your password again WITH 8 characters")

#7

def average(l):
  sum=0
  for i in l:
    sum+=i
  average=sum/len(l)
  return average
list_1=[1,2,3]
average(list_1)

#8

def count_vowels(a):
  l=[]
  for i in a:
    if(i in ['a','e','i','o','u']):
      l.append(i)
  return(len(list(set(l))))


count_vowels("aditya")


#9
import datetime

current_datetime = datetime.datetime.now()

print("Current Date and Time:", current_datetime)

#10
def add_numbers(num1, num2):
    try:

        num1 = float(num1)
        num2 = float(num2)

        result = num1 + num2
        return result
    except ValueError:

        return "Error: Please provide numeric inputs for addition."


input1 = input("Enter the first number: ")
input2 = input("Enter the second number: ")


sum_result = add_numbers(input1, input2)
print("Result:", sum_result)

#11
def get_integer_input(prompt):
    while True:
        try:
            user_input = int(input(prompt))
            return user_input
        except ValueError:
            print("Please enter a valid integer.")


try:
    num = get_integer_input("Please enter an integer: ")
    print("You entered:", num)
except KeyboardInterrupt:
    print("\nProgram terminated by user.")

#12
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")

#13
with open("hello_python.txt", "w") as file:
    file.write("Hello, Python!")

#14
with open("hello_python.txt", "r") as file:
    content = file.read()
    print("Content of the file before appending:", content)

#15
with open("hello_python.txt", "a") as file:
    file.write("\nThis is a new line appended!")


with open("hello_python.txt", "r") as file:
    updated_content = file.read()
    print("Updated content of the file:", updated_content)

