# -*- coding: utf-8 -*-
"""Random-forest-classifier-lvasdsusr-AdityaV-LAB1-MODIFIED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y1NXAIRoZkziA2QKYSCpseRyeFOlOVsC
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Read Data
df = pd.read_csv('/content/loan_approval.csv')

# Step 2: Replace Missing Values for Numeric Columns
# Extract numeric columns
numeric_cols = ['no_of_dependents', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
                'residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value']
imputer = SimpleImputer(strategy='median')
df[numeric_cols] = imputer.fit_transform(df[numeric_cols])

# Step 3: Convert Categorical Variables to Numerical using Label Encoding
label_encoder = LabelEncoder()
categorical_cols = ['education', 'self_employed']
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

# Step 4: Remove Outliers (assuming 'income_annum' is a key financial variable)
df_cleaned = df[(np.abs(df['income_annum'] - df['income_annum'].mean()) / df['income_annum'].std()) < 3]

# Step 5: Perform Exploratory Data Analysis (EDA)
# Summary Statistics
print(df_cleaned.describe())

# Visualization
sns.pairplot(df_cleaned)
plt.show()

# Correlation Analysis
corr_matrix = df_cleaned.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

# Step 6: Model Training and Testing
# Define features and target variable
X = df_cleaned.drop(['loan_id', 'loan_status'], axis=1)
y = df_cleaned['loan_status']

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_scaled, y_train)

# Step 7: Model Evaluation
# Predict on test set
y_pred = rf_classifier.predict(X_test_scaled)

# Classification Report
print(classification_report(y_test, y_pred))

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, cmap='Blues', fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()